In [1]:
#import dependencies
import pandas as pd
import pymongo
import requests
from bs4 import BeautifulSoup

In [2]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

In [5]:
# Define database and collection
db = client.nba_db
collection = db.Stadium_data

In [6]:
URL = "https://en.wikipedia.org/wiki/List_of_National_Basketball_Association_arenas"
wiki_url= requests.get(URL)
soup = BeautifulSoup(wiki_url.text, 'html.parser')
tables = soup.find_all('table', class_='sortable')
arena_data=pd.read_html(str(tables))
arena_data

[    Image                       Arena                    Location  \
 0     NaN     American Airlines Arena              Miami, Florida
 1     NaN    American Airlines Center               Dallas, Texas
 2     NaN                Amway Center            Orlando, Florida
 3     NaN                 AT&T Center          San Antonio, Texas
 4     NaN     Bankers Life Fieldhouse       Indianapolis, Indiana
 5     NaN             Barclays Center          Brooklyn, New York
 6     NaN           Capital One Arena            Washington, D.C.
 7     NaN                Chase Center   San Francisco, California
 8     NaN     Chesapeake Energy Arena     Oklahoma City, Oklahoma
 9     NaN                  FedExForum          Memphis, Tennessee
 10    NaN                Fiserv Forum        Milwaukee, Wisconsin
 11    NaN             Golden 1 Center      Sacramento, California
 12    NaN        Little Caesars Arena           Detroit, Michigan
 13    NaN       Madison Square Garden     New York City, New York
 14    NaN                 Moda Center            Portland, Oregon
 15    NaN                Pepsi Center            Denver, Colorado
 16    NaN  Rocket Mortgage FieldHouse             Cleveland, Ohio
 17    NaN            Scotiabank Arena            Toronto, Ontario
 18    NaN        Smoothie King Center      New Orleans, Louisiana
 19    NaN             Spectrum Center   Charlotte, North Carolina
 20    NaN              Staples Center     Los Angeles, California
 21    NaN              Staples Center     Los Angeles, California
 22    NaN            State Farm Arena            Atlanta, Georgia
 23    NaN  Talking Stick Resort Arena            Phoenix, Arizona
 24    NaN               Target Center      Minneapolis, Minnesota
 25    NaN                   TD Garden       Boston, Massachusetts
 26    NaN               Toyota Center              Houston, Texas
 27    NaN               United Center           Chicago, Illinois
 28    NaN     Vivint Smart Home Arena        Salt Lake City, Utah
 29    NaN          Wells Fargo Center  Philadelphia, Pennsylvania

                    Team(s)  Capacity   Opened       Ref(s)
 0               Miami Heat     19600     1999       [1][2]
 1         Dallas Mavericks     19200     2001       [1][3]
 2            Orlando Magic     18846     2010       [1][4]
 3        San Antonio Spurs     18418     2002       [1][5]
 4           Indiana Pacers     17923     1999       [1][6]
 5            Brooklyn Nets     17732     2012       [1][7]
 6       Washington Wizards     20356     1997       [1][8]
 7    Golden State Warriors     18064     2019   [1][9][10]
 8    Oklahoma City Thunder     18203     2002      [1][11]
 9        Memphis Grizzlies     17794     2004      [1][12]
 10         Milwaukee Bucks     17500     2018      [1][13]
 11        Sacramento Kings     17583     2016      [1][14]
 12         Detroit Pistons     20332     2017      [1][15]
 13         New York Knicks     19812  1968[a]      [1][16]
 14  Portland Trail Blazers     19441     1995      [1][17]
 15          Denver Nuggets     19520     1999      [1][18]
 16     Cleveland Cavaliers     19432     1994  [1][19][20]
 17         Toronto Raptors     19800     1999      [1][21]
 18    New Orleans Pelicans     16867     1999      [1][22]
 19       Charlotte Hornets     19077     2005      [1][23]
 20    Los Angeles Clippers     19068     1999      [1][24]
 21      Los Angeles Lakers     18997     1999      [1][24]
 22           Atlanta Hawks     18118     1999      [1][25]
 23            Phoenix Suns     18055     1992      [1][26]
 24  Minnesota Timberwolves     18978     1990      [1][27]
 25          Boston Celtics     18624     1995      [1][28]
 26         Houston Rockets     18055     2003      [1][29]
 27           Chicago Bulls     20917     1994      [1][30]
 28               Utah Jazz     18306     1991      [1][31]
 29      Philadelphia 76ers     20478     1996  [1][32][33]  ,
                                            Arena                  Team  \
 0  Inglewood Basketball and Entertainment Center  Los Angeles Clippers

                 Location  Capacity  Opening     Reference
 0  Inglewood, California     18000     2024  [34][35][36]  ]

In [7]:
nba_arenas=arena_data[0]
nba_arenas.head()

,Image,Arena,Location,Team(s),Capacity,Opened,Ref(s)
0,NaN,American Airlines Arena,"Miami, Florida",Miami Heat,19600,1999,[1][2]
1,NaN,American Airlines Center,"Dallas, Texas",Dallas Mavericks,19200,2001,[1][3]
2,NaN,Amway Center,"Orlando, Florida",Orlando Magic,18846,2010,[1][4]
3,NaN,AT&T Center,"San Antonio, Texas",San Antonio Spurs,18418,2002,[1][5]
4,NaN,Bankers Life Fieldhouse,"Indianapolis, Indiana",Indiana Pacers,17923,1999,[1][6]

In [8]:
nba_arenas_df=nba_arenas.drop(['Image','Opened','Ref(s)'],axis=1)
nba_arenas_df

,Arena,Location,Team(s),Capacity
0,American Airlines Arena,"Miami, Florida",Miami Heat,19600
1,American Airlines Center,"Dallas, Texas",Dallas Mavericks,19200
2,Amway Center,"Orlando, Florida",Orlando Magic,18846
3,AT&T Center,"San Antonio, Texas",San Antonio Spurs,18418
4,Bankers Life Fieldhouse,"Indianapolis, Indiana",Indiana Pacers,17923
5,Barclays Center,"Brooklyn, New York",Brooklyn Nets,17732
6,Capital One Arena,"Washington, D.C.",Washington Wizards,20356
7,Chase Center,"San Francisco, California",Golden State Warriors,18064
8,Chesapeake Energy Arena,"Oklahoma City, Oklahoma",Oklahoma City Thunder,18203
9,FedExForum,"Memphis, Tennessee",Memphis Grizzlies,17794
10,Fiserv Forum,"Milwaukee, Wisconsin",Milwaukee Bucks,17500
11,Golden 1 Center,"Sacramento, California",Sacramento Kings,17583
12,Little Caesars Arena,"Detroit, Michigan",Detroit Pistons,20332
13,Madison Square Garden,"New York City, New York",New York Knicks,19812
14,Moda Center,"Portland, Oregon",Portland Trail Blazers,19441
15,Pepsi Center,"Denver, Colorado",Denver Nuggets,19520
16,Rocket Mortgage FieldHouse,"Cleveland, Ohio",Cleveland Cavaliers,19432
17,Scotiabank Arena,"Toronto, Ontario",Toronto Raptors,19800
18,Smoothie King Center,"New Orleans, Louisiana",New Orleans Pelicans,16867
19,Spectrum Center,"Charlotte, North Carolina",Charlotte Hornets,19077
20,Staples Center,"Los Angeles, California",Los Angeles Clippers,19068
21,Staples Center,"Los Angeles, California",Los Angeles Lakers,18997
22,State Farm Arena,"Atlanta, Georgia",Atlanta Hawks,18118
23,Talking Stick Resort Arena,"Phoenix, Arizona",Phoenix Suns,18055
24,Target Center,"Minneapolis, Minnesota",Minnesota Timberwolves,18978
25,TD Garden,"Boston, Massachusetts",Boston Celtics,18624
26,Toyota Center,"Houston, Texas",Houston Rockets,18055
27,United Center,"Chicago, Illinois",Chicago Bulls,20917
28,Vivint Smart Home Arena,"Salt Lake City, Utah",Utah Jazz,18306
29,Wells Fargo Center,"Philadelphia, Pennsylvania",Philadelphia 76ers,20478

In [9]:
from opencage.geocoder import OpenCageGeocode
key = "06cbb655277e4d4a9b075579925aa006"  # get api key from:  https://opencagedata.com
geocoder = OpenCageGeocode(key)

In [10]:
list_lat = []   # create empty lists

list_long = []


for index, row in nba_arenas_df.iterrows(): # iterate over rows in dataframe

#     City = row['City']
#     State = row['State']       
    query = row['Location']  

    results = geocoder.geocode(query)   
    lat = results[0]['geometry']['lat']
    long = results[0]['geometry']['lng']

    list_lat.append(lat)
    list_long.append(long)

	
# create new columns from lists    

nba_arenas_df['lat'] = list_lat   

nba_arenas_df['lon'] = list_long
nba_arenas_df

,Arena,Location,Team(s),Capacity,lat,lon
0,American Airlines Arena,"Miami, Florida",Miami Heat,19600,25.774266,-80.193659
1,American Airlines Center,"Dallas, Texas",Dallas Mavericks,19200,32.776272,-96.796856
2,Amway Center,"Orlando, Florida",Orlando Magic,18846,28.542111,-81.379030
3,AT&T Center,"San Antonio, Texas",San Antonio Spurs,18418,29.424600,-98.495141
4,Bankers Life Fieldhouse,"Indianapolis, Indiana",Indiana Pacers,17923,39.768333,-86.158350
5,Barclays Center,"Brooklyn, New York",Brooklyn Nets,17732,40.650104,-73.949582
6,Capital One Arena,"Washington, D.C.",Washington Wizards,20356,38.894985,-77.036571
7,Chase Center,"San Francisco, California",Golden State Warriors,18064,37.779026,-122.419906
8,Chesapeake Energy Arena,"Oklahoma City, Oklahoma",Oklahoma City Thunder,18203,35.472989,-97.517054
9,FedExForum,"Memphis, Tennessee",Memphis Grizzlies,17794,35.149022,-90.051629
10,Fiserv Forum,"Milwaukee, Wisconsin",Milwaukee Bucks,17500,43.034993,-87.922497
11,Golden 1 Center,"Sacramento, California",Sacramento Kings,17583,38.581061,-121.493895
12,Little Caesars Arena,"Detroit, Michigan",Detroit Pistons,20332,42.331551,-83.046640
13,Madison Square Garden,"New York City, New York",New York Knicks,19812,40.712728,-74.006015
14,Moda Center,"Portland, Oregon",Portland Trail Blazers,19441,45.520247,-122.674195
15,Pepsi Center,"Denver, Colorado",Denver Nuggets,19520,39.739236,-104.984862
16,Rocket Mortgage FieldHouse,"Cleveland, Ohio",Cleveland Cavaliers,19432,41.505161,-81.693445
17,Scotiabank Arena,"Toronto, Ontario",Toronto Raptors,19800,43.653482,-79.383935
18,Smoothie King Center,"New Orleans, Louisiana",New Orleans Pelicans,16867,29.949932,-90.070116
19,Spectrum Center,"Charlotte, North Carolina",Charlotte Hornets,19077,35.227200,-80.843083
20,Staples Center,"Los Angeles, California",Los Angeles Clippers,19068,34.053691,-118.242766
21,Staples Center,"Los Angeles, California",Los Angeles Lakers,18997,34.053691,-118.242766
22,State Farm Arena,"Atlanta, Georgia",Atlanta Hawks,18118,33.749099,-84.390185
23,Talking Stick Resort Arena,"Phoenix, Arizona",Phoenix Suns,18055,33.448437,-112.074142
24,Target Center,"Minneapolis, Minnesota",Minnesota Timberwolves,18978,44.977300,-93.265469
25,TD Garden,"Boston, Massachusetts",Boston Celtics,18624,42.360253,-71.058291
26,Toyota Center,"Houston, Texas",Houston Rockets,18055,29.758938,-95.367697
27,United Center,"Chicago, Illinois",Chicago Bulls,20917,41.875562,-87.624421
28,Vivint Smart Home Arena,"Salt Lake City, Utah",Utah Jazz,18306,40.759620,-111.886798
29,Wells Fargo Center,"Philadelphia, Pennsylvania",Philadelphia 76ers,20478,39.952724,-75.163526

In [12]:
Stadium_data=nba_arenas_df.rename(columns = {'Team(s)':'TEAM' }, inplace = False)
Stadium_data.head()

,Arena,Location,TEAM,Capacity,lat,lon
0,American Airlines Arena,"Miami, Florida",Miami Heat,19600,25.774266,-80.193659
1,American Airlines Center,"Dallas, Texas",Dallas Mavericks,19200,32.776272,-96.796856
2,Amway Center,"Orlando, Florida",Orlando Magic,18846,28.542111,-81.379030
3,AT&T Center,"San Antonio, Texas",San Antonio Spurs,18418,29.424600,-98.495141
4,Bankers Life Fieldhouse,"Indianapolis, Indiana",Indiana Pacers,17923,39.768333,-86.158350

In [13]:
Stadium_data.reset_index(inplace=True)
arena_dict = Stadium_data.to_dict("records")
# Insert collection
collection.insert_many(arena_dict)